// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"todotom/go-gin-restful-api/forum"
	"todotom/go-gin-restful-api/postgres"
	"todotom/go-gin-restful-api/rest"
)

// Injectors from wire.go:

func InitializeContainer() Container {
	threadRepository := postgres.ProvideThreadRepository()
	getThreadsService := forum.ProvideGetThreadsService(threadRepository)
	getThreadsHandler := rest.ProvideGetThreadsHandler(getThreadsService)
	controller := rest.ProvideController(getThreadsHandler)
	container := ProvideContainer(controller)
	return container
}
